Simulation = "OmniState"
Servers = 2
Hosts = 2
BF = 2
BlocksPerDay = 144
FileBlock = "blocks-size.csv"
FileUnspent = "utxo-count.csv"
Scaling = 100
Bandwidth = 1000
IndividualStats = "true"
RunWait = 86400

SimulationDays, StateBlockFreq, timeStart, timeEnd, timeStep
365, 1, 1, 365, 1
365, 7, 1, 365, 1
