Simulation = "OmniState"
Servers = 2
Hosts = 2
BF = 2
BlocksPerDay = 144
FileBlock = "blocks-size.csv"
FileUnspent = "utxo-count.csv"
Scaling = 10000
Bandwidth = 1000
IndividualStats = "true"
RunWait = 86400

SimulationDays, StateBlockFreq, timeStart, timeEnd, timeStep
50, 1, 1, 50, 1
50, 7, 1, 50, 1
