Simulation = "OmniState"
Servers = 2
Hosts = 2
BF = 2
BlocksPerDay = 144
FileBlock = "blocks-size.csv"
FileUnspent = "utxo-count.csv"
Scaling = 1000
Bandwidth = 1000
IndividualStats = "true"
RunWait = 86400

SimulationDays, StateBlockFreq, timeStart, timeEnd, timeStep
50, 0, 1, 50, 1
50, 3, 1, 50, 1
50, 5, 1, 50, 1
50, 10, 1, 50, 1
100, 20, 1, 100, 1
