Simulation = "OmniState"
Servers = 2
Hosts = 3
BF = 2
BlocksPerDay = 14
FileBlock = "blocks-size.csv"
FileUnspent = "utxo-count.csv"
Scaling = 1000
Bandwidth = 1000
IndividualStats = "true"
SimulationDays = 20

StateBlockFreq, timeStart, timeEnd, timeStep
1, 1, 20, 1
7, 1, 20, 1
