Servers = 32
Simulation = "ServiceBNG"
#Simulation = "ByzCoin"
NumClientTxs = 350000
RunWait = 3000
CloseWait = 3000
Hosts= 600

Depth, Hosts, Blocksize, Threads, Rounds
5, 600, 4500, 1, 8
5, 600, 1000, 4, 20