Servers = 35
Simulation = "Service2BNG"
NumClientTxs = 80000
RunWait = 3000
CloseWait = 3000

BF, Hosts, Blocksize, Threads, Rounds, Shards, Auditors
3, 123, 17000, 1, 100, 2, 30
#3, 1230, 17000, 1, 100, 2, 30
